#ifndef GLOBALS_H
#define GLOBALS_H

const int SCREEN_WIDTH = 800;
const int SCREEN_HEIGHT = 600;

enum ID { PLAYER, ENEMY, BULLET, BORDER, MISC, EXPLOSION, };
enum STATE { TITLE, PLAYING, LOST, };

#endif
